### ISSUE TITLE
Is new PolyMC?

### ISSUE THREAD

**Issue by FITFC** [PrismLauncher/Translations#1]

**Comment by FelipeAzambuja** [comment]
I believe not, it's just a malicious repository trying to impersonate polymc

**Comment by FITFC** [comment]
Great, i download now

**Comment by FITFC** [comment]
> I believe not, it's just a malicious repository trying to impersonate polymc

Oh no my PC crashed, I think it was the malicious repository (I thought this was a good thing)

**Comment by FelipeAzambuja** [comment]
I DOAN FEELZ SAFE AUTHENTICATIN MAH MICROSOFT AKOWNT IN DIS PROJECT

**Comment by icemoss** [comment]
This is a launcher made by the non-corrupt Devs of PolyMC, as a successor to PolyMC. It crashed most likely because it is still dev builds, it's not ready for the public quite yet.
