### ISSUE TITLE
Error in polish translation

### ISSUE THREAD

**Issue by Silvobi** [PrismLauncher/Translations#14]
### Version of Prism Launcher

Prism Launcher 8.2

### Version of Qt

Qt 6.6.2

### Description of bug

On the following image as you can see instead of "następujące" it says "następujący"
It should say "Zamierzasz pobrać następując**e** modyfikacj**e**"
![obraz](https://github.com/PrismLauncher/PrismLauncher/assets/54009037/7054ab3e-1d7a-4fd4-8533-d998f2840436)

### Steps to reproduce

In main menu (using polish language of launcher), choose any instatnion and then go to:
Edytuj > Mody (should say "Modyfikacje" btw cuz there is no word in polish called "Mod") > Pobierz modyfikacje > Choose any modification > Wybierz modyfikacje do pobrania > Sprawdź i potwierdź
Then you will see the window with wrong translation

### Suspected cause

Just a wrong translation lol

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by TheKodeToad** [comment]
You can fix it yourself here if you want!
https://hosted.weblate.org/projects/prismlauncher/launcher/pl/

**Comment by Silvobi** [comment]
oh right, thanks for letting me know!
![obraz](https://github.com/PrismLauncher/Translations/assets/54009037/340f0e8d-0107-448c-bb42-60099c36b127)
here, I hope I didn't messed smth up ._.

**Comment by Scrumplex** [comment]
Fixed in https://github.com/PrismLauncher/Translations/commit/eacf69f201124031a11c589c8968ee5530b7d205
