### ISSUE TITLE
File selection for the "Add to Minecraft.jar" option does not show .zip files if certain languages are set

### ISSUE THREAD

**Issue by TheVorkMan** [PrismLauncher/Translations#18]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.3

### Version of Qt

Qt 6.3.3

### Description of bug

When Russian, Esperanto or Traditional Chinese languages set, file selection should show .jar and .zip files for the "Add to Minecraft.jar" option, but it's shows only .jar.

### Steps to reproduce

Choose русский, Esperanto, 繁體中文 language from the settings.
Create new instance for any version and then go to the "Edit...".
Version -> "Add to Minecraft.jar"
Find the directory where the zip archive should be located.

### Suspected cause

There may have been an update to the translation system, and some translations were not updated.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
This is then a issue with the translation for that languages

**Comment by Trial97** [comment]
should be fixed by these commits: https://github.com/PrismLauncher/Translations/compare/eef0097512d4...e5c2e78489c9
You may need to restart prism or wait until translation are invalidated
